INSERT INTO public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) VALUES (1, 'pbkdf2_sha256$150000$3aGdeqfDrQRe$kSFGSQsU4gQNy47ETQUe/4h10BomG185PtLMTmgdyhc=', '2019-07-22 13:32:48.991608', false, 'test', 'Max', 'Mustermann', 'max@test.de', false, true, '2019-07-22 11:39:40.630843');
INSERT INTO public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) VALUES (2, 'pbkdf2_sha256$150000$Cmd3V6WoQe0k$EsUUGnmqTj6LauphU+cYcxMaYJUtyLrT4eL9pRS/C9Q=', null, false, 'anonym', 'Arno', 'Nühm', 'arno@test.de', false, true, '2019-07-23 10:53:02.085431');
INSERT INTO public.auth_group (id, name) VALUES (1, 'User manager');
INSERT INTO public.auth_group (id, name) VALUES (2, 'Annotator');
INSERT INTO public.auth_group_description (id, description, group_id) VALUES (1, 'User able to create, update and delete other users.', 1);
INSERT INTO public.auth_group_description (id, description, group_id) VALUES (2, 'User able to annotate data.', 2);
INSERT INTO public.auth_user_groups (id, user_id, group_id) VALUES (1, 1, 1);
INSERT INTO public.auth_user_groups (id, user_id, group_id) VALUES (2, 1, 2);
INSERT INTO public.auth_user_groups (id, user_id, group_id) VALUES (3, 2, 2);
INSERT INTO public.collection (id, basepath, description, name) VALUES (1, 'Test', 'Test collection for development purposes', 'Test');
-- INSERT INTO public.concept (id, name, description, collectionid) VALUES (1, 'Entwicklung', 'Concept for development purposes', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (1, 'Alte_Person', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (2, 'Baby', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (3, 'Badezimmer', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (4, 'Baeckerei_innen', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (5, 'Band_(Rock_Pop)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (6, 'Bibliothek_innen', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (7, 'Blitz', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (8, 'Brandenburger_Tor_(Berlin)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (9, 'Chor', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (10, 'Denkmal_Statue', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (11, 'Dom_St', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (12, 'Elbpanorama_(Dresden)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (13, 'Erfurter_Dom_(Erfurt)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (14, 'Fahnenappell', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (15, 'Fernsehgeraet', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (16, 'Fernsehkamera', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (17, 'Fernsehturm_(Berlin)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (18, 'Fleischerei_innen', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (19, 'Frau_Elster', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (20, 'Friedenstaube', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (21, 'Friedhof', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (22, 'Friseur_innen', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (23, 'Fruehling', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (24, 'Gelbes_Elend_(Bautzen)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (25, 'Gewandhaus_(Leipzig)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (26, 'Grillen', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (27, 'Hammer_und_Sichel', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (28, 'Herbst', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (29, 'Herr_Fuchs', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (30, 'Hund_(Haustier)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (31, 'Jeans', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (32, 'Jugendweihe', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (33, 'KFZ-Kennzeichen_Nummernschild', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (34, 'Karl-Marx-Monument_(Karl-Marx-Stadt_Chemnitz)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (35, 'Katze_(Haustier)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (36, 'Kind', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (37, 'Kino_innen', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (38, 'Klassenzimmer', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (39, 'Kreml_(Moskau)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (40, 'Kulturpalast_(Warschau)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (41, 'Landkarte', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (42, 'Lange_Strasse_(Rostock)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (43, 'Litfasssaeule', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (44, 'Magdeburger_Dom_(Magdeburg)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (45, 'Markt', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (46, 'Meissner_Dom_(Meissen)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (47, 'Minirock_-kleid', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (48, 'Nachrichtensprecher', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (49, 'Nacht_aussen', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (50, 'Naehmaschine', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (51, 'Nahaufnahme', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (52, 'Naumburger_Dom_(Naumburg)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (53, 'Olympische_Ringe_(Logo)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (54, 'Orchester', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (55, 'Ortsschild', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (56, 'Picknick', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (57, 'Pilzkopf-Frisur', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (58, 'Pittiplatsch', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (59, 'Pressekonferenz', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (60, 'Rathausturm_(Gera)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (61, 'Regen', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (62, 'Regieraum', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (63, 'Rollstuhlfahrer', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (64, 'Roter_Turm_(Halle)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (65, 'Rotes_Rathaus_(Berlin)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (66, 'Sanssouci_(Potsdam)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (67, 'Schlosskirche_(Wittenberg)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (68, 'Schweriner_Schloss_(Schwerin)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (69, 'Silhouette', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (70, 'Sonnenauf-_untergang', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (71, 'Spremberger_Turm_(Cottbus)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (72, 'Stadttheater_(Weimar)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (73, 'Strassenschild', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (74, 'Tagungspodium', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (75, 'Teepott_und_Leuchtturm_(Rostock-Warnemuende)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (76, 'Telefon', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (77, 'Thomaskirche_(Leipzig)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (78, 'Totale', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (79, 'Trachten', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (80, 'Traktor', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (81, 'Tram_Strassenbahn', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (82, 'Turmspitze', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (83, 'U-Bahn', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (84, 'Ue-Wagen', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (85, 'Unihochhaus_City-Hochhaus', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (86, 'Uniturm_(Jena)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (87, 'Unterwasseraufnahme', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (88, 'Vogelperspektive', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (89, 'Wandern_(in_der_Natur)', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (90, 'Weihnachten', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (91, 'Weltall', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (92, 'Wohnzimmer', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (93, 'Zeichentrick_Zeichnung', 1);
INSERT INTO public.concept (id, name, collectionid) VALUES (94, 'Zeitung_Zeitschrift', 1);
SELECT setval(pg_get_serial_sequence('"auth_group_description"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auth_group_description";
SELECT setval(pg_get_serial_sequence('"collection"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "collection";
SELECT setval(pg_get_serial_sequence('"concept"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "concept";
SELECT setval(pg_get_serial_sequence('"concepttype"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "concepttype";
SELECT setval(pg_get_serial_sequence('"dataset"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "dataset";
SELECT setval(pg_get_serial_sequence('"datasetimage"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "datasetimage";
SELECT setval(pg_get_serial_sequence('"evaluation"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "evaluation";
SELECT setval(pg_get_serial_sequence('"image"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "image";
SELECT setval(pg_get_serial_sequence('"imageconceptannotation"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "imageconceptannotation";
SELECT setval(pg_get_serial_sequence('"imageconceptprediction"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "imageconceptprediction";
SELECT setval(pg_get_serial_sequence('"intervalconceptannotation"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "intervalconceptannotation";
SELECT setval(pg_get_serial_sequence('"model"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "model";
SELECT setval(pg_get_serial_sequence('"video"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "video";
SELECT setval(pg_get_serial_sequence('"videoframe"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "videoframe";
SELECT setval(pg_get_serial_sequence('"videointerval"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "videointerval";
SELECT setval(pg_get_serial_sequence('"videoshot"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "videoshot";
INSERT INTO public.collection (id, basepath, description, name) VALUES (2, 'Test_Persons', 'Test collection persons', 'Test_Persons');
INSERT INTO public.person (id, name, description, collectionid) VALUES (1, 'Abesser_Doris', 'Actress', 2);
INSERT INTO public.person (id, name, description, collectionid) VALUES (2, 'Gauck_Joachim', '', 2);
INSERT INTO public.person (id, name, description, collectionid) VALUES (3, 'Merkel_Angela', '',2);
SELECT setval(pg_get_serial_sequence('"person"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "person";