# Generated by Django 2.2.5 on 2019-10-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageurl',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
