# Generated by Django 2.2.6 on 2019-11-10 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20191105_1403'),
    ]

    operations = [
        migrations.RenameModel('Concepttype', 'Classtype'),
        migrations.RenameField('Concept', 'concepttypeid', 'classtypeid'),

        migrations.RenameModel('Concept', 'Class'),
        migrations.RenameField('Imageconceptannotation', 'conceptid', 'classid'),
        migrations.RenameField('Imageconceptprediction', 'conceptid', 'classid'),
        migrations.RenameField('Intervalconceptannotation', 'conceptid', 'classid'),

        migrations.CreateModel(
            name='Imageannotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('difficult', models.BooleanField()),
                ('groundtruth', models.BooleanField()),
            ],
            options={
                'db_table': 'imageannotation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Imageprediction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'imageprediction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Intervalannotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('difficult', models.BooleanField()),
                ('groundtruth', models.BooleanField()),
                ('startframe', models.IntegerField()),
                ('endframe', models.IntegerField()),
            ],
            options={
                'db_table': 'intervalannotation',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='imageconceptprediction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='imageconceptprediction',
            name='classid',
        ),
        migrations.RemoveField(
            model_name='imageconceptprediction',
            name='imageid',
        ),
        migrations.RemoveField(
            model_name='imageconceptprediction',
            name='modelid',
        ),
        migrations.AlterUniqueTogether(
            name='intervalconceptannotation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='intervalconceptannotation',
            name='classid',
        ),
        migrations.RemoveField(
            model_name='intervalconceptannotation',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='intervalconceptannotation',
            name='videoid',
        ),
        migrations.AlterField(
            model_name='class',
            name='classtypeid',
            field=models.ForeignKey(blank=True, db_column='classtypeid', null=True,
                                    on_delete=django.db.models.deletion.PROTECT, to='base.Classtype'),
        ),
        migrations.AlterModelTable(
            name='class',
            table='class',
        ),
        migrations.AlterModelTable(
            name='classtype',
            table='classtype',
        ),
        migrations.DeleteModel(
            name='Imageconceptannotation',
        ),
        migrations.DeleteModel(
            name='Imageconceptprediction',
        ),
        migrations.DeleteModel(
            name='Intervalconceptannotation',
        ),
        migrations.AddField(
            model_name='intervalannotation',
            name='classid',
            field=models.ForeignKey(db_column='classid', on_delete=django.db.models.deletion.PROTECT, to='base.Class'),
        ),
        migrations.AddField(
            model_name='intervalannotation',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.PROTECT,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intervalannotation',
            name='videoid',
            field=models.ForeignKey(db_column='videoid', on_delete=django.db.models.deletion.PROTECT, to='base.Video'),
        ),
        migrations.AddField(
            model_name='imageprediction',
            name='classid',
            field=models.ForeignKey(db_column='classid', on_delete=django.db.models.deletion.PROTECT, to='base.Class'),
        ),
        migrations.AddField(
            model_name='imageprediction',
            name='imageid',
            field=models.ForeignKey(db_column='imageid', on_delete=django.db.models.deletion.PROTECT, to='base.Image'),
        ),
        migrations.AddField(
            model_name='imageprediction',
            name='modelid',
            field=models.ForeignKey(db_column='modelid', on_delete=django.db.models.deletion.PROTECT, to='base.Model'),
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='classid',
            field=models.ForeignKey(db_column='classid', on_delete=django.db.models.deletion.PROTECT, to='base.Class'),
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='imageid',
            field=models.ForeignKey(db_column='imageid', on_delete=django.db.models.deletion.PROTECT, to='base.Image'),
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.PROTECT,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='intervalannotation',
            unique_together={('videoid', 'classid')},
        ),
        migrations.AlterUniqueTogether(
            name='imageprediction',
            unique_together={('imageid', 'classid', 'modelid')},
        ),
        migrations.AlterUniqueTogether(
            name='imageannotation',
            unique_together={('imageid', 'classid')},
        ),
    ]
