# Generated by Django 2.2.7 on 2019-11-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20191110_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='userid',
        ),
    ]
