# Generated by Django 2.2.12 on 2020-06-02 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200426_2003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasetimage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='datasetimage',
            name='datasetid',
        ),
        migrations.RemoveField(
            model_name='datasetimage',
            name='imageid',
        ),
        migrations.AlterUniqueTogether(
            name='imagepersonannotation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='imagepersonannotation',
            name='imageid',
        ),
        migrations.RemoveField(
            model_name='imagepersonannotation',
            name='personid',
        ),
        migrations.RemoveField(
            model_name='imagepersonannotation',
            name='userid',
        ),
        migrations.AlterUniqueTogether(
            name='intervalannotation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='intervalannotation',
            name='classid',
        ),
        migrations.RemoveField(
            model_name='intervalannotation',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='intervalannotation',
            name='videoid',
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='person',
            name='collectionid',
        ),
        migrations.RemoveField(
            model_name='videointerval',
            name='videoid',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='path',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='datasetid',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='model',
            name='description',
        ),
        migrations.RemoveField(
            model_name='model',
            name='name',
        ),
        migrations.RemoveField(
            model_name='model',
            name='trainingsetid',
        ),
        migrations.RemoveField(
            model_name='model',
            name='validationsetid',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='classid',
            field=models.ForeignKey(db_column='classid', default=1, on_delete=django.db.models.deletion.PROTECT, to='base.Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='precision',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='path',
            field=models.CharField(default='not-a-path/', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='Datasetimage',
        ),
        migrations.DeleteModel(
            name='Imagepersonannotation',
        ),
        migrations.DeleteModel(
            name='Intervalannotation',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Videointerval',
        ),
    ]
