# Generated by Django 2.2.12 on 2020-06-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20200602_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='path',
            new_name='model_path',
        ),
        migrations.AddField(
            model_name='model',
            name='inference_stored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model',
            name='log_path',
            field=models.CharField(default='non-path/', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('modelid', 'classid')},
        ),
    ]
