# Generated by Django 2.2.12 on 2020-06-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200602_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='log_path',
        ),
        migrations.RemoveField(
            model_name='model',
            name='model_path',
        ),
        migrations.AddField(
            model_name='model',
            name='dir_name',
            field=models.CharField(default='non-path/', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
