# Generated by Django 2.2.13 on 2020-08-07 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0014_auto_20200607_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bboxannotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
                ('classid', models.ForeignKey(db_column='classid', on_delete=django.db.models.deletion.PROTECT, to='base.Class')),
                ('imageid', models.ForeignKey(db_column='imageid', on_delete=django.db.models.deletion.PROTECT, to='base.Image')),
                ('userid', models.ForeignKey(db_column='userid', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bboxannotation',
                'managed': True,
                'unique_together': {('imageid', 'classid')},
            },
        ),
    ]
