# Generated by Django 2.2.15 on 2020-12-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20201201_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='collectionid',
        ),
        migrations.RemoveField(
            model_name='video',
            name='frames',
        ),
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbbasepath',
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
