# Generated by Django 2.2.15 on 2021-01-13 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20201205_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bboxannotation',
            name='classid',
            field=models.ForeignKey(db_column='classid', null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Class'),
        ),
        migrations.AlterUniqueTogether(
            name='bboxannotation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bboxannotation',
            constraint=models.UniqueConstraint(fields=('imageid', 'classid'), name='unique_with_classid'),
        ),
    ]
